### ISSUE TITLE
コードレビュー 2022-10-16 指摘事項

### ISSUE THREAD

**Issue by Samemura** [ysk91/libe_tokyo_office#42]
# レビュー内容と雑感

1.5時間程度（時間の制約がないと区切りがなくなってしまうため）で見れるところを全体的にざっくりみて、気になるところを挙げさせて頂きました。
主に、Model, Controller, Routing周りを優先して、私が得意ではないCSSは簡単なチェックのみとしています。

## 良いところ
- 全体的にシンプルに記述されていて、好感がもてる実装だと思いました。
- インテグレーションテストをきちんと書いているのはとても素晴らしいと思います。

## 今後の改善の方向性
細かい点を改善事項であげさせて頂きましたが、半分くらいはツールでチェックできるところになるため、落ち着いたらどこかのタイミングで以下ツールを導入してリファクタリングしてみてください。確実に良いコードになるため、ポートフォリオとしてレベルアップできると思いますし、コードを書いていく上で矯正具の役割をしてくれて自然と良いコードがかけるようになると思います。
- Rubocop: Ruby/Railsのコード全体
- StyleLint: SCSS

# 指摘事項

## 不具合

- ここは、 `@user = User.find_by(id: cookies.encrypted[:user_id])` が正しそうです。
https://github.com/ysk91/libe_tokyo_office/blob/0758a694e2429bde4946b1f236c0a2a842173ffd/app/controllers/application_controller.rb#L21-L24

## 改善案
- READMEに何も書いていない。開発環境の構築方法や、テストの方法などを記述すると良いです。本番やステージングのURLもあると有用です。
- Dotenvは開発環境でも使った方が良さそうに思いました。何で環境変数を管理されているのか、分かりづらいので。
書き方も `group :production do` にさらに、 `groups: [:production]` は不要です。
https://github.com/ysk91/libe_tokyo_office/blob/6162668efbcedc8a69b3f7e15b2df0b6afaa88d7/Gemfile#L84-L85
- gitigoreした方がいいと思います。
  - https://github.com/ysk91/libe_tokyo_office/blob/development/.byebug_history
- 不要なトラブルを避けるために、ファイル名を日本語は避けた方がいいです。
https://github.com/ysk91/libe_tokyo_office/blob/6162668efbcedc8a69b3f7e15b2df0b6afaa88d7/app/assets/images/%E3%82%B3%E3%83%83%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%AA%E3%83%B3.png

### routingについて
- RESTfulを意識して、 `/map` は MapsController#show にした方が良いと思います。
https://github.com/ysk91/libe_tokyo_office/blob/88f63b8bc5560748baa8112cb44226b769ed5e3e/config/routes.rb#L4
- `/users/login` などのログイン・ログアウトについては、 パスはそのままでいいので `Users::SessionController#new` などにまとめるとControllerの処理含めてスッキリすると思います。

### Controllerについて
- Controllerでは、パスヘルパーを使いましょう。 例： `root_path`
routingが変わってもコードを変更する必要がなくります。https://github.com/ysk91/libe_tokyo_office/blob/704772c2b9af9ec1c331293ff7b610855aa70c2a/app/controllers/users_controller.rb#L16
- `@current_user` はメソッドにしてメモ化すると、使い勝手がよく大概そういう使い方してます。
https://github.com/ysk91/libe_tokyo_office/blob/0758a694e2429bde4946b1f236c0a2a842173ffd/app/controllers/application_controller.rb#L17
```
def current_user
  @current_user ||= begin
今までのset_current_userの処理
  end
end
```
- `logged_in?` を使いましょう
https://github.com/ysk91/libe_tokyo_office/blob/0758a694e2429bde4946b1f236c0a2a842173ffd/app/controllers/application_controller.rb#L35
- `@resent_messages` と `@random_messages`, `@new_message` とするとベターな名前になると思います。
https://github.com/ysk91/libe_tokyo_office/blob/5c971a60cb6f0a874e007ebc07a898cdae6606d1/app/controllers/messages_controller.rb#L5-L7

### Modelについて
- `Info` モデルは名前が抽象的すぎるので、 `Recomendation` とかの方が望ましいかと思います。
- 括弧ありとなしで、どちらかに書き方を統一しましょう。概ね、この場合は括弧なしが一般的だと思います。
https://github.com/ysk91/libe_tokyo_office/blob/72422b86ff0988619c8d1e6e4dabfb88f30920ef/app/models/user.rb#L18-L19
- `belongs_to` は暗黙的に `presence: true` なので、改めてのvalidationは不要です。
https://github.com/ysk91/libe_tokyo_office/blob/16e87c08e1f3a71e27cbc2b4ae9dfaeafb6ddb0e/app/models/review.rb#L5-L6

### Viewについて

- この場合、`""` は不要です。
`link_to(message.user.name` にできます。
https://github.com/ysk91/libe_tokyo_office/blob/12ce9e627b1b354194aa5e2c4590cbfd8e1c50f3/app/views/messages/index.html.erb#L17

### seed.rb

- 冗長な書き方なので、シンプルにまとめましょう。また、`create` に失敗するかもしれないので、 `create!` を使いましょう。他の箇所も同様にリファクタリングできます。
https://github.com/ysk91/libe_tokyo_office/blob/d2fe10afeaf5ab0c0aa7d79f05056e7b3e961f92/db/seeds.rb#L36-L35
```
Genre.create({name:"ランチ"}, {name:"ディナー"}, ...
```

**Comment by Samemura** [comment]
@ysk91 レビュー完了しました！
ちなみに、GitHubアカウントにもプロフィール画像を何かしら設定しておいて頂けると、視認・認知されやすいので、できるときに設定してみてくださいー

**Comment by ysk91** [comment]
# 質問



## gitignore

> Dotenvは開発環境でも使った方が良さそうに思いました。何で環境変数を管理されているのか、分かりづらいので。

sqlite3の環境設定値を隠すということでしょうか？
`.env.development`に何を記載すべきなのかを教えて頂きたいです。
`config/database.yml`には`ENV`変数は使用していません。

## RESTful
なかなか難しい概念です、、
少しずつ慣れていきます。
(感覚的に「変かもなぁ〜」という気はしていました。)

## `@current_user`のメモ化
Railsチュートリアルでも「メモ化」という言葉は出てきて、あまり理解していませんでした。

> メソッド呼び出しの結果を変数に保存し、次回以降の呼び出しで再利用する手法を[メモ化（memoization）](https://ja.wikipedia.org/wiki/%E3%83%A1%E3%83%A2%E5%8C%96)と呼びます。

```ruby
if @current_user.nil?
  @current_user = User.find_by(id: session[:user_id])
else
  @current_user
end
```
↓↓↓↓↓↓
```ruby
@current_user = @current_user || User.find_by(id: session[:user_id])
```
↓↓↓↓↓↓
```ruby
@current_user ||= User.find_by(id: session[:user_id])
```
の流れをおさらいします。

### 参考
[Railsチュートリアル8章](https://railstutorial.jp/chapters/basic_login?version=6.0#cha-basic_login)

## 関数名について

> @resent_messages と @random_messages, @new_message とするとベターな名前になると思います。
> Info モデルは名前が抽象的すぎるので、 Recomendation とかの方が望ましいかと思います。

この辺は「リーダブルコード」を読めば身につくのでしょうか？
Samemuraさんの英語レベルも聞きたいです。

## `belongs_to`について
これは単純に知りませんでした。
でも言われてみればそうですね。
Recommendationでもgenre_idをバリデーションしていたので、リファクタリングしました。

## seed.rb

> 他の箇所も同様にリファクタリングできます。

他の箇所がどこなのかを教えて頂きたいです。


## scssファイルについて
今はコントローラ別に分けて`application.scss`で参照させているのですが、その必要はなかったりしますか？
何となくメンテしにくいなぁと思っているので、`application.scss`に合体しても問題ないのであれば合体させたいです。

**Comment by Samemura** [comment]
> # 質問
> ## Dotenv
> > Dotenvは開発環境でも使った方が良さそうに思いました。何で環境変数を管理されているのか、分かりづらいので。
> 
> sqlite3の環境設定値を隠すということでしょうか？ `.env.development`に何を記載すべきなのかを教えて頂きたいです。 `config/database.yml`には`ENV`変数は使用していません。

Development環境で環境変数の設定が必要なことが多いので、その場合はDotenvはを使うといいよーという感じでした。

> ## RESTful
> なかなか難しい概念です、、 少しずつ慣れていきます。 (感覚的に「変かもなぁ〜」という気はしていました。)
> 

基本のメソッド(show, indexなど)以外のメソッドを使っている時は問題あるかもーという感覚です

> ## `@current_user`のメモ化
> Railsチュートリアルでは下記のようにメモ化を説明しています。
> 
> > メソッド呼び出しの結果を変数に保存し、次回以降の呼び出しで再利用する手法を[メモ化（memoization）](https://ja.wikipedia.org/wiki/%E3%83%A1%E3%83%A2%E5%8C%96)と呼びます。
> 
> 今回の場合、applicationコントローラで定義し、`before_action`することでメモ化しているという認識でしたが、間違っていますか？ 少し詳しく聞きたいです。
> 

Lazy loadingの考え方で、なるべくあとに実行されるようにするといいです。そのためにメモ化が必要です。

> ## 関数名について
> > @resent_messages と @random_messages, @new_message とするとベターな名前になると思います。
> > Info モデルは名前が抽象的すぎるので、 Recomendation とかの方が望ましいかと思います。
> 
> この辺は「リーダブルコード」を読めば身につくのでしょうか？ Samemuraさんの英語レベルも聞きたいです。

まあまあ英語はできます。
こういうのを見るといいかもです。
https://qiita.com/genzouw/items/35022fa96c120e67c637

> ## `belongs_to`について
> これは単純に知りませんでした。 でも言われてみればそうですね。 Recommendationでもgenre_idをバリデーションしていたので、リファクタリングしました。
> 
> ## seed.rb
> > 他の箇所も同様にリファクタリングできます。
> 
> 他の箇所がどこなのかを教えて頂きたいです。
> 
> ## scssファイルについて
> 今はコントローラ別に分けて`application.scss`で参照させているのですが、その必要はなかったりしますか？ 何となくメンテしにくいなぁと思っているので、`application.scss`に合体しても問題ないのであれば合体させたいです。

デザインのパーツごとにファイル分ける感じとか、いろいろやり方はあるかと思います。

**Comment by ysk91** [comment]
コードレビューありがとうございました！
指摘から約1週間ですべて適用することができました。
本番環境にもマージ済です。

`seeds.rb`のリファクタリングについて、Qiitaにまとめさせていただきました。
https://qiita.com/ysk91_engineer/items/e9f687b2873721fcb4d9
